### ISSUE TITLE
JOSS: Dependencies

### ISSUE THREAD

**Issue by mhubii** [ARC-OPT/wbc_ros#10]
`package.xml` / `CMakeLists.txt` dependency mismatch:

package.xml:
```xml
  <depend>geometry_msgs</depend>
  <depend>controller_interface</depend>
  <depend>controller_manager</depend>
  <depend>xacro</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>sensor_msgs</depend>
  <depend>trajectory_msgs</depend>
  <depend>realtime_tools</depend>
  <depend>joint_state_broadcaster</depend>
  <depend>std_msgs</depend>
  <depend>generate_parameter_library</depend>
```

CMake:
```CMake
  rclcpp
  realtime_tools
  std_msgs
  geometry_msgs
  trajectory_msgs
  wbc_msgs
  sensor_msgs
  pluginlib
  rclcpp_lifecycle
  controller_interface
  hardware_interface
  generate_parameter_library
```

- `package.xml` should state `exec_depend` on
    - `controller_manager`
    - `xacro`
    - `robot_state_publisher` (missing)
    - `joint_state_broadcaster` 

Example in readme https://github.com/ARC-OPT/wbc_ros#examples should not need to highlight manual installation if `package.xml` was configured correctly (usually handled through `rosdep`) (optional)

Refers to https://github.com/openjournals/joss-reviews/issues/6696

**Comment by dmronga** [comment]
@mhubii  I fixed the dependencies. However, I cannot add wbc_msgs to package.xml as this package is not the ros index. Therefore, the slightly complicated install instructions [here](https://arc-opt.github.io/Documentation/installation/installation_ros2.html). If you know a way around this, please advice.

**Comment by mhubii** [comment]
hi  @dmronga , yes, you can add `--ignore-src` or `-i` to `rosdep`, you can read the doc through `rosdep --help`
