### ISSUE TITLE
ros2_control: Is it possible to use messages instead of reference interfaces?

### ISSUE THREAD

**Issue by dmronga** [ARC-OPT/wbc_ros#5]
Passing the control output via the reference interfaces is ugly, since it require serialization of the data, which has to be interpreted correctly by the next controller. Also, if there are many tasks, the number of reference interfaces will explode. Is it possible to use message passing instead

**Comment by mhubii** [comment]
Not sure I get this issue right. The idea of `ros2_control` is to be topic-free (latency, single access point). The controllers that you implement should only reference basic command / state interface. 

The tasks themselves should be topics that the controller expects as input, which is what you have done (from what I can tell). Should this issue therefore be closed?

Refers to https://github.com/openjournals/joss-reviews/issues/6696

**Comment by dmronga** [comment]
@mhubii  This is a design problem of ros2_control (in my opinion) that data between chained controllers (and back/forth to the hardware interface) is passed via double arrays. To me this meant that I have to serialize the data myself, which is error prone and hard to maintain. In WBC I possibly have many reference interfaces (depending on the WBC configuration) with different data types and things get complicated very quickly. So my idea was to use ros2 nodes and ros2 messages instead. In theory the underlying DDS should do shared memory copy, when configured correctly and when 2 ros nodes are executed in the same process. But I get that message passing via topics is never real-time? And we also found that the overhead when you send messages with 1KHz can be significant. I was hoping that there is a different way for providing the state and reference interfaces in ros2_control

**Comment by mhubii** [comment]
hm okay I see, feel free to ignore this for the review btw. Just adding relevant issues:

- Inter-process communication over shared memory requires components (which `ros2_control` to my best knowledge doesn't support right now: https://github.com/ros-controls/ros2_control/issues/330, https://github.com/ros-controls/ros2_control/issues/1261)
- Other people seem to have related issues with chainable controllers https://github.com/ros-controls/ros2_control/issues/1710

**Comment by dmronga** [comment]
Thanks for hints, I will check the options someday I guess. I always wondered if ros2_control is suited for more complex  control architecture like MPC, WBC, ...
