### ISSUE TITLE
missing dependency to wbc_msgs

### ISSUE THREAD

**Issue by annaborn** [ARC-OPT/wbc_ros#9]
@dmronga 
Hello Dennis!
could you please add in package.xml the dependency to wbc_msgs?
Thank you in advance!

**Comment by dmronga** [comment]
Hi Anna, the problem is that rosdep install will not work anymore if I do that, as wbc_msgs is not in the ROS index. A workaround for the problem is to build wbc_msgs first and then wbc_ros. I would be glad if you have a better solution....

**Comment by annaborn** [comment]
@dmronga 
I did not think about it. I just cross against this issue with other third-part library, that was added in package.xml as dependency. 
I am currently looking for the solution. I let you know, if I will find smth. :)

Thank you for your reply!

**Comment by mhubii** [comment]
re-using this issue for https://github.com/openjournals/joss-reviews/issues/6696

The common approach in ROS is to specify a `repos.yaml` (refer e.g. https://github.com/ros-controls/ros2_control/blob/master/ros2_control.humble.repos) file and to clone dependencies via `vcstool`.

**Comment by dmronga** [comment]
Added repos.yaml and updates install instruction accordingly. I believe I will leave the wbc install separately for  now
